### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by srisub1** [oreillymedia/Learning-OpenCV-3_examples#1]
I only see a README

**Comment by derderderder** [comment]
Me too!!!

**Comment by LonShapiro** [comment]
still only the README

**Comment by eudoxos** [comment]
> We apologize that all of the code from the book is not up yet, but it will be uploaded as soon as possible. Please bear with us, the authors and the staff are very busy people and we are doing our best.

This is a joke, right? You are a business charging money for that. Hire more people if you are "very busy" and don't make people who bought the book suffer from your poor management.

**Comment by garybradski** [comment]
It's coming, now up through 15. In a perfect world, there would be perfect management ... but my world is deeply imperfect for many reasons, some of which you can google for.

**Comment by eudoxos** [comment]
That is about delivering what we pay for, not about inherent imperfection. Whatever.

**Comment by srisub1** [comment]
Its ok. We are glad its up there. Gary, after googling, found that you are
otherwise preoccupied, so this is totally understandable.

Thanks for writing a great book that gave me a jump start on OpenCV

Sri
