### ISSUE TITLE
  Does 《learning opencv 3》 have a plan for translating into Chinese?

### ISSUE THREAD

**Issue by jsxyhelu** [oreillymedia/Learning-OpenCV-3_examples#33]
I wonder if there is any plan to translate 《learning opencv 3》 into Chinese?
      And as a machine vision engineer, can I join the plan?
      Many Thank。

**Comment by garybradski** [comment]
I think there is a guy, a professor signed up. Sure, you can join. Last time, the quality of the book and the translation was not good. I'd like to have a good version on good paper this time, so you can help check that. The Japanese version was done very well (he found many errors the English readers missed).

**Comment by jsxyhelu** [comment]
Great news!
How can I join? Can you provide some contact information? For example, the professor's email.
It would be very helpful if you recommended me.

**Comment by garybradski** [comment]
What is your direct email?

**Comment by jsxyhelu** [comment]
sorry for late.
jsxyhelu [AT] foxmail.com
is my direct email

**Comment by jsxyhelu** [comment]
HI，
 jsxyhelu@foxmail.com is my direct emailand  I am an computer vision engineer from china,It would be my honor to be able to participate in translation.
thanks.
HELU



------------------ 原始邮件 ------------------
发件人: "Gary Bradski";<notifications@github.com>;
发送时间: 2017年6月23日(星期五) 下午4:27
收件人: "oreillymedia/Learning-OpenCV-3_examples"<Learning-OpenCV-3_examples@noreply.github.com>; 
抄送: "jsxyhelu"<jsxyhelu@foxmail.com>; "Author"<author@noreply.github.com>; 
主题: Re: [oreillymedia/Learning-OpenCV-3_examples] Does 《learning opencv 3》 have a plan for translating into Chinese? (#33)



What is your direct email?
