### ISSUE TITLE
is "cv::smooth() "out of use?

### ISSUE THREAD

**Issue by jsxyhelu** [oreillymedia/Learning-OpenCV-3_examples#36]
in chapter 8 ,page 321
"3.  Load an interesting image, and then blur it with cv::smooth() using a Gaussian
filter.
a.  Set param1=param2=9. Try several settings of param3 (e.g., 1, 4, and 6). Display
the results.
b.  Set param1=param2=0 before setting param3 to 1, 4, and 6. Display the results.
Are they different? Why?
c.  Use  param1=param2=0  again,  but  this  time  set  param3=1  and  param4=9.
Smooth the picture and display the results.
d.  Repeat Exercise 3c but with param3=9 and param4=1. Display the results.
e.  Now  smooth  the  image  once  with  the  settings  of  Exercise  3c  and  once  with
the settings of Exercise 3d. Display the results.
f.  Compare    the    results    in    Exercise    3e    with    smoothings    that    use
param3=param4=9 and param3=param4=0 (i.e., a 9 × 9 filter). Are the results the
same? Why or why not?"
as i kown,cv::smooth() is out of use for quite a long time (am i right,i cant find it neither in the code nor in the book) ,then how to solve this problem,and where is the param1?param2?

**Comment by garybradski** [comment]
You are right, the smoothing functions are now:
cv::blur
cv::GaussianBlur
cv::medianBlur
cv::bilateralFilter

I am forwarding this to OReilly errata for Learning OpenCV 3

**Comment by jsxyhelu** [comment]
OK,have done
