### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by masacate** [oreillymedia/Learning-OpenCV-3_examples#5]
Please,
some feedback aboutwhen the example's code is planned to be available?

**Comment by garybradski** [comment]
It's coming. See the new code loaded as of today

**Comment by masacate** [comment]
Great!

Thnanks

________________________________
De: Gary Bradski <notifications@github.com>
Enviado: miércoles, 24 de mayo de 2017 22:05
Para: oreillymedia/Learning-OpenCV-3_examples
Cc: masacate; Author
Asunto: Re: [oreillymedia/Learning-OpenCV-3_examples] Source Code (#5)


Closed #5<https://github.com/oreillymedia/Learning-OpenCV-3_examples/issues/5>.
